### ISSUE TITLE
AI more training data

### ISSUE THREAD

**Issue by Mayerch1** [Mayerch1/Applied-AI-Technologies#19]
especially humans without mask and non-human images

trying to lead the ai into detecting uncoverd mouth/nose

**Comment by Gabriel-Goldschmitt** [comment]
https://www.kaggle.com/vtech6/medical-masks-dataset?
bounding box
good  = with maske
bad = without maske 

https://www.kaggle.com/ashishjangra27/face-mask-12k-images-dataset
Big dataset 
6000 without Mask
6000 with Mask
